language: node_js

matrix:
  fast_finish: true
  include:
  - node_js: 10
    env: ESLINT_VERSION=6
  - node_js: 10
    env: ESLINT_VERSION=5

script:
- npm test
- npm uninstall eslint-config-prettier
- npm install eslint@$ESLINT_VERSION
- npm run test:integration
